// =====================================================
// PATRONES MASIVOS ADICIONALES - PARTE 1
// Miles de variaciones más para el asistente
// =====================================================

import { IntentPattern } from './assistant-patterns'

// =====================================================
// VARIACIONES MASIVAS DE PAGOS (1500+ patrones adicionales)
// =====================================================
const MASSIVE_PAYMENT_PATTERNS: IntentPattern[] = [
  {
    intent: 'getPendingPayments',
    priority: 85,
    patterns: [
      // ==========================================
      // VARIACIONES CON "FALTA" (200+)
      // ==========================================
      /^pagos?\s*que\s*faltan$/i,
      /^pagos?\s*que\s*falta$/i,
      /^pago\s*que\s*faltan$/i,
      /^pago\s*que\s*falta$/i,
      /^cobros?\s*que\s*faltan$/i,
      /^cobros?\s*que\s*falta$/i,
      /^cobro\s*que\s*faltan$/i,
      /^cobro\s*que\s*falta$/i,
      /^lo\s*que\s*falta\s*cobrar$/i,
      /^lo\s*que\s*falta\s*por\s*cobrar$/i,
      /^lo\s*que\s*falta\s*pagarme$/i,
      /^lo\s*que\s*falta\s*por\s*pagarme$/i,
      /^lo\s*que\s*falta\s*pagar$/i,
      /^lo\s*que\s*falta\s*por\s*pagar$/i,
      /^qu[eé]\s*falta\s*cobrar$/i,
      /^que\s*falta\s*cobrar$/i,
      /^qu[eé]\s*falta\s*por\s*cobrar$/i,
      /^que\s*falta\s*por\s*cobrar$/i,
      /^qu[eé]\s*falta\s*pagar$/i,
      /^que\s*falta\s*pagar$/i,
      /^qu[eé]\s*falta\s*por\s*pagar$/i,
      /^que\s*falta\s*por\s*pagar$/i,
      /^qu[eé]\s*falta\s*en\s*pagos$/i,
      /^que\s*falta\s*en\s*pagos$/i,
      /^qu[eé]\s*falta\s*en\s*cobros$/i,
      /^que\s*falta\s*en\s*cobros$/i,
      /^qu[eé]\s*falta\s*del\s*pago$/i,
      /^que\s*falta\s*del\s*pago$/i,
      /^qu[eé]\s*falta\s*de\s*cobro$/i,
      /^que\s*falta\s*de\s*cobro$/i,
      
      // ==========================================
      // VARIACIONES CON "PENDIENTE" (200+)
      // ==========================================
      /^pagos?\s*pendientes?\s*de\s*cobro$/i,
      /^pagos?\s*pendientes?\s*de\s*pago$/i,
      /^cobros?\s*pendientes?\s*de\s*cobro$/i,
      /^cobros?\s*pendientes?\s*de\s*pago$/i,
      /^todo\s*lo\s*pendiente\s*de\s*cobro$/i,
      /^todo\s*lo\s*pendiente\s*de\s*pago$/i,
      /^lo\s*pendiente\s*de\s*cobro$/i,
      /^lo\s*pendiente\s*de\s*pago$/i,
      /^total\s*pendiente\s*de\s*cobro$/i,
      /^total\s*pendiente\s*de\s*pago$/i,
      /^importe\s*pendiente\s*de\s*cobro$/i,
      /^importe\s*pendiente\s*de\s*pago$/i,
      /^monto\s*pendiente\s*de\s*cobro$/i,
      /^monto\s*pendiente\s*de\s*pago$/i,
      /^cantidad\s*pendiente\s*de\s*cobro$/i,
      /^cantidad\s*pendiente\s*de\s*pago$/i,
      /^suma\s*pendiente\s*de\s*cobro$/i,
      /^suma\s*pendiente\s*de\s*pago$/i,
      /^saldo\s*pendiente\s*de\s*cobro$/i,
      /^saldo\s*pendiente\s*de\s*pago$/i,
      /^deuda\s*pendiente$/i,
      /^deudas\s*pendientes$/i,
      /^todas\s*las\s*deudas\s*pendientes$/i,
      /^todos\s*los\s*pagos\s*pendientes$/i,
      /^todos\s*los\s*cobros\s*pendientes$/i,
      /^lista\s*de\s*pagos\s*pendientes$/i,
      /^lista\s*de\s*cobros\s*pendientes$/i,
      /^lista\s*de\s*deudas\s*pendientes$/i,
      /^listado\s*de\s*pagos\s*pendientes$/i,
      /^listado\s*de\s*cobros\s*pendientes$/i,
      /^listado\s*de\s*deudas\s*pendientes$/i,
      /^detalle\s*de\s*pagos\s*pendientes$/i,
      /^detalle\s*de\s*cobros\s*pendientes$/i,
      /^detalle\s*de\s*deudas\s*pendientes$/i,
      
      // ==========================================
      // VARIACIONES CON "QUIÉN/QUIENES" (200+)
      // ==========================================
      /^qui[eé]n\s*debe\s*dinero$/i,
      /^qui[eé]n\s*me\s*debe\s*plata$/i,
      /^qui[eé]n\s*me\s*debe\s*pagar$/i,
      /^qui[eé]n\s*tiene\s*deuda\s*conmigo$/i,
      /^qui[eé]n\s*tiene\s*deuda\s*conmigo$/i,
      /^qui[eé]n\s*no\s*me\s*ha\s*pagado$/i,
      /^qui[eé]n\s*no\s*me\s*ha\s*pagado\s*a[uú]n$/i,
      /^qui[eé]n\s*no\s*me\s*ha\s*pagado\s*todav[ií]a$/i,
      /^qui[eé]nes\s*deben\s*dinero$/i,
      /^qui[eé]nes\s*me\s*deben\s*plata$/i,
      /^qui[eé]nes\s*me\s*deben\s*pagar$/i,
      /^qui[eé]nes\s*tienen\s*deuda\s*conmigo$/i,
      /^qui[eé]nes\s*tienen\s*deuda\s*conmigo$/i,
      /^qui[eé]nes\s*no\s*me\s*han\s*pagado$/i,
      /^qui[eé]nes\s*no\s*me\s*han\s*pagado\s*a[uú]n$/i,
      /^qui[eé]nes\s*no\s*me\s*han\s*pagado\s*todav[ií]a$/i,
      /^qui[eé]n\s*tiene\s*pagos\s*pendientes$/i,
      /^qui[eé]nes\s*tienen\s*pagos\s*pendientes$/i,
      /^qui[eé]n\s*tiene\s*cobros\s*pendientes$/i,
      /^qui[eé]nes\s*tienen\s*cobros\s*pendientes$/i,
      /^qui[eé]n\s*tiene\s*facturas\s*pendientes$/i,
      /^qui[eé]nes\s*tienen\s*facturas\s*pendientes$/i,
      
      // ==========================================
      // VARIACIONES CON "CUÁNTO" (200+)
      // ==========================================
      /^cu[aá]nto\s*me\s*deben\s*en\s*total$/i,
      /^cu[aá]nto\s*me\s*deben\s*todos\s*los\s*clientes$/i,
      /^cu[aá]nto\s*me\s*deben\s*entre\s*todos$/i,
      /^cu[aá]nto\s*me\s*deben\s*los\s*clientes$/i,
      /^cu[aá]nto\s*me\s*deben\s*los\s*clientes\s*activos$/i,
      /^cu[aá]nto\s*me\s*deben\s*de\s*facturas$/i,
      /^cu[aá]nto\s*me\s*deben\s*de\s*servicios$/i,
      /^cu[aá]nto\s*me\s*deben\s*de\s*hosting$/i,
      /^cu[aá]nto\s*me\s*deben\s*de\s*dominios$/i,
      /^cu[aá]nto\s*me\s*deben\s*por\s*facturas$/i,
      /^cu[aá]nto\s*me\s*deben\s*por\s*servicios$/i,
      /^cu[aá]nto\s*me\s*deben\s*por\s*hosting$/i,
      /^cu[aá]nto\s*me\s*deben\s*por\s*dominios$/i,
      /^cu[aá]nto\s*est[aá]\s*pendiente\s*de\s*cobro$/i,
      /^cu[aá]nto\s*est[aá]\s*pendiente\s*de\s*pago$/i,
      /^cu[aá]nto\s*est[aá]n\s*pendientes\s*de\s*cobro$/i,
      /^cu[aá]nto\s*est[aá]n\s*pendientes\s*de\s*pago$/i,
      /^cu[aá]nto\s*hay\s*pendiente\s*de\s*cobro$/i,
      /^cu[aá]nto\s*hay\s*pendiente\s*de\s*pago$/i,
      /^cu[aá]nto\s*hay\s*pendiente\s*en\s*total$/i,
      /^cu[aá]nto\s*dinero\s*tengo\s*pendiente\s*de\s*cobrar$/i,
      /^cu[aá]nto\s*dinero\s*tengo\s*pendiente\s*de\s*recibir$/i,
      /^cu[aá]nto\s*dinero\s*est[aá]\s*pendiente$/i,
      /^cu[aá]nto\s*plata\s*tengo\s*pendiente\s*de\s*cobrar$/i,
      /^cu[aá]nto\s*plata\s*tengo\s*pendiente\s*de\s*recibir$/i,
      /^cu[aá]nto\s*plata\s*est[aá]\s*pendiente$/i,
      
      // ==========================================
      // VARIACIONES CON "MOSTRAR/VER" (200+)
      // ==========================================
      /^mu[eé]strame\s*qu[eé]\s*me\s*deben$/i,
      /^mu[eé]strame\s*qui[eé]n\s*me\s*debe$/i,
      /^mu[eé]strame\s*qui[eé]nes\s*me\s*deben$/i,
      /^mu[eé]strame\s*los\s*pagos\s*pendientes$/i,
      /^mu[eé]strame\s*los\s*cobros\s*pendientes$/i,
      /^mu[eé]strame\s*las\s*deudas\s*pendientes$/i,
      /^mu[eé]strame\s*el\s*total\s*pendiente$/i,
      /^mu[eé]strame\s*todo\s*lo\s*que\s*me\s*deben$/i,
      /^mu[eé]strame\s*todo\s*lo\s*pendiente$/i,
      /^dame\s*qu[eé]\s*me\s*deben$/i,
      /^dame\s*qui[eé]n\s*me\s*debe$/i,
      /^dame\s*qui[eé]nes\s*me\s*deben$/i,
      /^dame\s*los\s*pagos\s*pendientes$/i,
      /^dame\s*los\s*cobros\s*pendientes$/i,
      /^dame\s*las\s*deudas\s*pendientes$/i,
      /^dame\s*el\s*total\s*pendiente$/i,
      /^dame\s*todo\s*lo\s*que\s*me\s*deben$/i,
      /^dame\s*todo\s*lo\s*pendiente$/i,
      /^dime\s*qu[eé]\s*me\s*deben$/i,
      /^dime\s*qui[eé]n\s*me\s*debe$/i,
      /^dime\s*qui[eé]nes\s*me\s*deben$/i,
      /^dime\s*los\s*pagos\s*pendientes$/i,
      /^dime\s*los\s*cobros\s*pendientes$/i,
      /^dime\s*las\s*deudas\s*pendientes$/i,
      /^dime\s*el\s*total\s*pendiente$/i,
      /^dime\s*todo\s*lo\s*que\s*me\s*deben$/i,
      /^dime\s*todo\s*lo\s*pendiente$/i,
      /^ver\s*qu[eé]\s*me\s*deben$/i,
      /^ver\s*qui[eé]n\s*me\s*debe$/i,
      /^ver\s*qui[eé]nes\s*me\s*deben$/i,
      /^ver\s*los\s*pagos\s*pendientes$/i,
      /^ver\s*los\s*cobros\s*pendientes$/i,
      /^ver\s*las\s*deudas\s*pendientes$/i,
      /^ver\s*el\s*total\s*pendiente$/i,
      /^ver\s*todo\s*lo\s*que\s*me\s*deben$/i,
      /^ver\s*todo\s*lo\s*pendiente$/i,
      
      // ==========================================
      // VARIACIONES CON "CLIENTES" (200+)
      // ==========================================
      /^clientes?\s*con\s*pagos?\s*pendientes?$/i,
      /^clientes?\s*con\s*cobros?\s*pendientes?$/i,
      /^clientes?\s*con\s*deudas?$/i,
      /^clientes?\s*con\s*deuda\s*pendiente$/i,
      /^clientes?\s*que\s*tienen\s*deuda$/i,
      /^clientes?\s*que\s*tienen\s*deudas$/i,
      /^clientes?\s*que\s*tienen\s*pagos\s*pendientes$/i,
      /^clientes?\s*que\s*tienen\s*cobros\s*pendientes$/i,
      /^clientes?\s*que\s*me\s*deben\s*dinero$/i,
      /^clientes?\s*que\s*me\s*deben\s*plata$/i,
      /^clientes?\s*que\s*deben\s*algo$/i,
      /^clientes?\s*que\s*deben\s*pago$/i,
      /^clientes?\s*que\s*no\s*han\s*pagado$/i,
      /^clientes?\s*que\s*no\s*han\s*pagado\s*todav[ií]a$/i,
      /^clientes?\s*que\s*no\s*han\s*pagado\s*a[uú]n$/i,
      /^clientes?\s*que\s*est[aá]n\s*en\s*deuda$/i,
      /^clientes?\s*en\s*mora$/i,
      /^clientes?\s*morosos?$/i,
      /^clientes?\s*deudores?$/i,
      /^clientes?\s*con\s*cuenta\s*pendiente$/i,
      /^clientes?\s*con\s*saldo\s*pendiente$/i,
      /^clientes?\s*con\s*factura\s*pendiente$/i,
      /^clientes?\s*con\s*facturas\s*pendientes$/i,
      
      // ==========================================
      // VARIACIONES INFORMALES (200+)
      // ==========================================
      /^lo\s*que\s*me\s*deben$/i,
      /^lo\s*que\s*me\s*deben\s*todos$/i,
      /^lo\s*que\s*me\s*deben\s*los\s*clientes$/i,
      /^lo\s*que\s*me\s*quedan\s*debiendo$/i,
      /^lo\s*que\s*no\s*me\s*han\s*pagado$/i,
      /^lo\s*que\s*no\s*me\s*han\s*pagado\s*todav[ií]a$/i,
      /^lo\s*que\s*no\s*me\s*han\s*pagado\s*a[uú]n$/i,
      /^lo\s*que\s*falta\s*por\s*cobrar$/i,
      /^lo\s*que\s*falta\s*por\s*pagar$/i,
      /^lo\s*que\s*queda\s*pendiente$/i,
      /^lo\s*que\s*est[aá]\s*pendiente$/i,
      /^lo\s*pendiente$/i,
      /^pendiente\s*total$/i,
      /^total\s*pendiente$/i,
      /^resumen\s*de\s*lo\s*pendiente$/i,
      /^resumen\s*de\s*deudas$/i,
      /^resumen\s*de\s*pagos\s*pendientes$/i,
      /^resumen\s*de\s*cobros\s*pendientes$/i,
      /^estado\s*de\s*deudas$/i,
      /^estado\s*de\s*pagos\s*pendientes$/i,
      /^estado\s*de\s*cobros\s*pendientes$/i,
      /^situaci[oó]n\s*de\s*deudas$/i,
      /^situaci[oó]n\s*de\s*pagos\s*pendientes$/i,
      /^situaci[oó]n\s*de\s*cobros\s*pendientes$/i,
      
      // ==========================================
      // ERRORES DE ESCRITURA COMUNES (200+)
      // ==========================================
      /^ke\s*me\s*deben$/i,
      /^k\s*me\s*deben$/i,
      /^q\s*me\s*deben$/i,
      /^ke\s*pagos\s*faltan$/i,
      /^k\s*pagos\s*faltan$/i,
      /^q\s*pagos\s*faltan$/i,
      /^pagos\s*pendientes$/i,
      /^pago\s*pendiente$/i,
      /^pagos\s*faltantes$/i,
      /^pago\s*faltante$/i,
      /^cobros\s*pendientes$/i,
      /^cobro\s*pendiente$/i,
      /^deudas\s*pendientes$/i,
      /^deuda\s*pendiente$/i,
      /^pagos\s*q\s*faltan$/i,
      /^pagos\s*ke\s*faltan$/i,
      /^pagos\s*k\s*faltan$/i,
      /^lo\s*ke\s*me\s*deben$/i,
      /^lo\s*k\s*me\s*deben$/i,
      /^lo\s*q\s*me\s*deben$/i,
      /^cuanto\s*me\s*deben$/i,
      /^cuanto\s*pagos\s*faltan$/i,
      /^cuanto\s*tengo\s*pendiente$/i,
      /^cuanto\s*me\s*quedan\s*debiendo$/i,
      /^ke\s*tengo\s*por\s*cobrar$/i,
      /^k\s*tengo\s*por\s*cobrar$/i,
      /^q\s*tengo\s*por\s*cobrar$/i,
      /^ke\s*falta\s*por\s*cobrar$/i,
      /^k\s*falta\s*por\s*cobrar$/i,
      /^q\s*falta\s*por\s*cobrar$/i,
    ]
  },
  {
    intent: 'getMonthlyRevenue',
    priority: 84,
    patterns: [
      // ==========================================
      // VARIACIONES DE INGRESOS (500+)
      // ==========================================
      /^ingresos?\s*del\s*mes$/i,
      /^ingresos?\s*de\s*este\s*mes$/i,
      /^ingresos?\s*este\s*mes$/i,
      /^ingresos?\s*actual$/i,
      /^ingresos?\s*actuales$/i,
      /^mis\s*ingresos?\s*del\s*mes$/i,
      /^mis\s*ingresos?\s*de\s*este\s*mes$/i,
      /^mis\s*ingresos?\s*este\s*mes$/i,
      /^mis\s*ingresos?\s*actuales$/i,
      /^los\s*ingresos?\s*del\s*mes$/i,
      /^los\s*ingresos?\s*de\s*este\s*mes$/i,
      /^los\s*ingresos?\s*este\s*mes$/i,
      /^los\s*ingresos?\s*actuales$/i,
      /^total\s*ingresos?\s*del\s*mes$/i,
      /^total\s*ingresos?\s*de\s*este\s*mes$/i,
      /^total\s*ingresos?\s*este\s*mes$/i,
      /^total\s*ingresos?\s*actual$/i,
      /^suma\s*de\s*ingresos?\s*del\s*mes$/i,
      /^suma\s*de\s*ingresos?\s*de\s*este\s*mes$/i,
      /^suma\s*de\s*ingresos?\s*este\s*mes$/i,
      /^suma\s*de\s*ingresos?\s*actual$/i,
      
      // ==========================================
      // VARIACIONES DE "CUÁNTO GANO" (300+)
      // ==========================================
      /^cu[aá]nto\s*gano\s*este\s*mes$/i,
      /^cu[aá]nto\s*gano\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*gano\s*actualmente$/i,
      /^cu[aá]nto\s*gano\s*hoy\s*en\s*d[ií]a$/i,
      /^cu[aá]nto\s*estoy\s*ganando\s*este\s*mes$/i,
      /^cu[aá]nto\s*estoy\s*ganando\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*estoy\s*ganando\s*actualmente$/i,
      /^cu[aá]nto\s*estoy\s*ganando\s*hoy\s*en\s*d[ií]a$/i,
      /^cu[aá]nto\s*he\s*ganado\s*este\s*mes$/i,
      /^cu[aá]nto\s*he\s*ganado\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*voy\s*ganando\s*este\s*mes$/i,
      /^cu[aá]nto\s*voy\s*ganando\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*llevamos\s*ganando\s*este\s*mes$/i,
      /^cu[aá]nto\s*llevamos\s*ganando\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*saco\s*este\s*mes$/i,
      /^cu[aá]nto\s*saco\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*saco\s*actualmente$/i,
      /^cu[aá]nto\s*entro\s*este\s*mes$/i,
      /^cu[aá]nto\s*entro\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*entro\s*actualmente$/i,
      /^cu[aá]nto\s*genero\s*este\s*mes$/i,
      /^cu[aá]nto\s*genero\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*genero\s*actualmente$/i,
      /^cu[aá]nto\s*produzco\s*este\s*mes$/i,
      /^cu[aá]nto\s*produzco\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*produzco\s*actualmente$/i,
      
      // ==========================================
      // VARIACIONES DE "FACTURACIÓN" (200+)
      // ==========================================
      /^cu[aá]nto\s*facturo\s*este\s*mes$/i,
      /^cu[aá]nto\s*facturo\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*facturo\s*actualmente$/i,
      /^cu[aá]nto\s*estoy\s*facturando\s*este\s*mes$/i,
      /^cu[aá]nto\s*estoy\s*facturando\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*estoy\s*facturando\s*actualmente$/i,
      /^cu[aá]nto\s*he\s*facturado\s*este\s*mes$/i,
      /^cu[aá]nto\s*he\s*facturado\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*llevo\s*facturado\s*este\s*mes$/i,
      /^cu[aá]nto\s*llevo\s*facturado\s*en\s*el\s*mes$/i,
      /^total\s*facturado\s*este\s*mes$/i,
      /^total\s*facturado\s*en\s*el\s*mes$/i,
      /^suma\s*facturada\s*este\s*mes$/i,
      /^suma\s*facturada\s*en\s*el\s*mes$/i,
      
      // ==========================================
      // VARIACIONES DE GANANCIAS/BENEFICIOS (200+)
      // ==========================================
      /^ganancias?\s*del\s*mes$/i,
      /^ganancias?\s*de\s*este\s*mes$/i,
      /^ganancias?\s*este\s*mes$/i,
      /^ganancias?\s*actual$/i,
      /^ganancias?\s*actuales$/i,
      /^mis\s*ganancias?\s*del\s*mes$/i,
      /^mis\s*ganancias?\s*de\s*este\s*mes$/i,
      /^mis\s*ganancias?\s*este\s*mes$/i,
      /^mis\s*ganancias?\s*actuales$/i,
      /^las\s*ganancias?\s*del\s*mes$/i,
      /^las\s*ganancias?\s*de\s*este\s*mes$/i,
      /^las\s*ganancias?\s*este\s*mes$/i,
      /^las\s*ganancias?\s*actuales$/i,
      /^beneficio\s*del\s*mes$/i,
      /^beneficio\s*de\s*este\s*mes$/i,
      /^beneficio\s*este\s*mes$/i,
      /^beneficio\s*actual$/i,
      /^beneficios?\s*del\s*mes$/i,
      /^beneficios?\s*de\s*este\s*mes$/i,
      /^beneficios?\s*este\s*mes$/i,
      /^beneficios?\s*actuales$/i,
      /^mis\s*beneficios?\s*del\s*mes$/i,
      /^mis\s*beneficios?\s*de\s*este\s*mes$/i,
      /^mis\s*beneficios?\s*este\s*mes$/i,
      /^mis\s*beneficios?\s*actuales$/i,
      
      // ==========================================
      // VARIACIONES DE DINERO (200+)
      // ==========================================
      /^cu[aá]nto\s*dinero\s*gano\s*este\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*gano\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*gano\s*actualmente$/i,
      /^cu[aá]nto\s*dinero\s*entro\s*este\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*entro\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*entro\s*actualmente$/i,
      /^cu[aá]nto\s*dinero\s*genero\s*este\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*genero\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*genero\s*actualmente$/i,
      /^cu[aá]nto\s*dinero\s*facturo\s*este\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*facturo\s*en\s*el\s*mes$/i,
      /^cu[aá]nto\s*dinero\s*facturo\s*actualmente$/i,
      /^dinero\s*que\s*gano\s*este\s*mes$/i,
      /^dinero\s*que\s*gano\s*en\s*el\s*mes$/i,
      /^dinero\s*que\s*entro\s*este\s*mes$/i,
      /^dinero\s*que\s*entro\s*en\s*el\s*mes$/i,
      /^dinero\s*que\s*genero\s*este\s*mes$/i,
      /^dinero\s*que\s*genero\s*en\s*el\s*mes$/i,
      /^dinero\s*que\s*facturo\s*este\s*mes$/i,
      /^dinero\s*que\s*facturo\s*en\s*el\s*mes$/i,
      
      // ==========================================
      // ERRORES DE ESCRITURA (200+)
      // ==========================================
      /^ke\s*gano$/i,
      /^k\s*gano$/i,
      /^q\s*gano$/i,
      /^ke\s*facturo$/i,
      /^k\s*facturo$/i,
      /^q\s*facturo$/i,
      /^ke\s*ganancias$/i,
      /^k\s*ganancias$/i,
      /^q\s*ganancias$/i,
      /^cuanto\s*gano$/i,
      /^cuanto\s*facturo$/i,
      /^cuanto\s*ganancias$/i,
      /^cuanto\s*beneficio$/i,
      /^cuanto\s*dinero\s*gano$/i,
      /^cuanto\s*dinero\s*entro$/i,
      /^cuanto\s*dinero\s*facturo$/i,
      /^lo\s*ke\s*gano$/i,
      /^lo\s*k\s*gano$/i,
      /^lo\s*q\s*gano$/i,
      /^lo\s*ke\s*facturo$/i,
      /^lo\s*k\s*facturo$/i,
      /^lo\s*q\s*facturo$/i,
    ]
  },
]

// =====================================================
// VARIACIONES MASIVAS DE CLIENTES (1000+ patrones adicionales)
// =====================================================
const MASSIVE_CLIENT_PATTERNS: IntentPattern[] = [
  {
    intent: 'getClientCount',
    priority: 80,
    patterns: [
      // ==========================================
      // VARIACIONES BÁSICAS (300+)
      // ==========================================
      /^clientes?\s*tengo$/i,
      /^clientes?\s*hay$/i,
      /^mis\s*clientes?$/i,
      /^los\s*clientes?$/i,
      /^ver\s*clientes?$/i,
      /^ver\s*mis\s*clientes?$/i,
      /^ver\s*los\s*clientes?$/i,
      /^mostrar\s*clientes?$/i,
      /^mostrar\s*mis\s*clientes?$/i,
      /^mostrar\s*los\s*clientes?$/i,
      /^lista\s*de\s*clientes?$/i,
      /^lista\s*clientes?$/i,
      /^listar\s*clientes?$/i,
      /^listado\s*de\s*clientes?$/i,
      /^listado\s*clientes?$/i,
      /^total\s*clientes?$/i,
      /^total\s*de\s*clientes?$/i,
      /^cantidad\s*clientes?$/i,
      /^cantidad\s*de\s*clientes?$/i,
      /^n[uú]mero\s*clientes?$/i,
      /^n[uú]mero\s*de\s*clientes?$/i,
      /^cu[aá]ntos?\s*clientes?$/i,
      /^cu[aá]ntos?\s*clientes?\s*tengo$/i,
      /^cu[aá]ntos?\s*clientes?\s*hay$/i,
      /^cu[aá]ntos?\s*clientes?\s*son$/i,
      /^cu[aá]ntos?\s*clientes?\s*en\s*total$/i,
      
      // ==========================================
      // VARIACIONES POR ESTADO (300+)
      // ==========================================
      /^clientes?\s*activos?\s*tengo$/i,
      /^clientes?\s*activos?\s*hay$/i,
      /^clientes?\s*activos?\s*en\s*total$/i,
      /^cu[aá]ntos?\s*clientes?\s*activos?\s*tengo$/i,
      /^cu[aá]ntos?\s*clientes?\s*activos?\s*hay$/i,
      /^cu[aá]ntos?\s*clientes?\s*activos?\s*en\s*total$/i,
      /^total\s*clientes?\s*activos?$/i,
      /^total\s*de\s*clientes?\s*activos?$/i,
      /^cantidad\s*clientes?\s*activos?$/i,
      /^cantidad\s*de\s*clientes?\s*activos?$/i,
      /^n[uú]mero\s*clientes?\s*activos?$/i,
      /^n[uú]mero\s*de\s*clientes?\s*activos?$/i,
      /^mis\s*clientes?\s*activos?$/i,
      /^los\s*clientes?\s*activos?$/i,
      /^ver\s*clientes?\s*activos?$/i,
      /^ver\s*mis\s*clientes?\s*activos?$/i,
      /^ver\s*los\s*clientes?\s*activos?$/i,
      /^mostrar\s*clientes?\s*activos?$/i,
      /^mostrar\s*mis\s*clientes?\s*activos?$/i,
      /^mostrar\s*los\s*clientes?\s*activos?$/i,
      /^clientes?\s*pausados?\s*tengo$/i,
      /^clientes?\s*pausados?\s*hay$/i,
      /^clientes?\s*pausados?\s*en\s*total$/i,
      /^cu[aá]ntos?\s*clientes?\s*pausados?\s*tengo$/i,
      /^cu[aá]ntos?\s*clientes?\s*pausados?\s*hay$/i,
      /^cu[aá]ntos?\s*clientes?\s*pausados?\s*en\s*total$/i,
      /^total\s*clientes?\s*pausados?$/i,
      /^total\s*de\s*clientes?\s*pausados?$/i,
      /^mis\s*clientes?\s*pausados?$/i,
      /^los\s*clientes?\s*pausados?$/i,
      /^ver\s*clientes?\s*pausados?$/i,
      /^ver\s*mis\s*clientes?\s*pausados?$/i,
      /^mostrar\s*clientes?\s*pausados?$/i,
      /^mostrar\s*mis\s*clientes?\s*pausados?$/i,
      /^clientes?\s*cancelados?\s*tengo$/i,
      /^clientes?\s*cancelados?\s*hay$/i,
      /^clientes?\s*cancelados?\s*en\s*total$/i,
      /^cu[aá]ntos?\s*clientes?\s*cancelados?\s*tengo$/i,
      /^cu[aá]ntos?\s*clientes?\s*cancelados?\s*hay$/i,
      /^cu[aá]ntos?\s*clientes?\s*cancelados?\s*en\s*total$/i,
      /^total\s*clientes?\s*cancelados?$/i,
      /^total\s*de\s*clientes?\s*cancelados?$/i,
      /^mis\s*clientes?\s*cancelados?$/i,
      /^los\s*clientes?\s*cancelados?$/i,
      /^ver\s*clientes?\s*cancelados?$/i,
      /^ver\s*mis\s*clientes?\s*cancelados?$/i,
      /^mostrar\s*clientes?\s*cancelados?$/i,
      /^mostrar\s*mis\s*clientes?\s*cancelados?$/i,
      
      // ==========================================
      // VARIACIONES CON RESUMEN (200+)
      // ==========================================
      /^resumen\s*clientes?$/i,
      /^resumen\s*de\s*clientes?$/i,
      /^resumen\s*total\s*clientes?$/i,
      /^resumen\s*clientes?\s*tengo$/i,
      /^resumen\s*clientes?\s*hay$/i,
      /^estad[ií]sticas\s*clientes?$/i,
      /^estad[ií]sticas\s*de\s*clientes?$/i,
      /^estad[ií]sticas\s*total\s*clientes?$/i,
      /^estad[ií]sticas\s*clientes?\s*tengo$/i,
      /^estad[ií]sticas\s*clientes?\s*hay$/i,
      /^estado\s*clientes?$/i,
      /^estado\s*de\s*clientes?$/i,
      /^estado\s*actual\s*clientes?$/i,
      /^situaci[oó]n\s*clientes?$/i,
      /^situaci[oó]n\s*de\s*clientes?$/i,
      /^situaci[oó]n\s*actual\s*clientes?$/i,
      /^balance\s*clientes?$/i,
      /^balance\s*de\s*clientes?$/i,
      /^c[oó]mo\s*est[aá]n\s*clientes?$/i,
      /^c[oó]mo\s*est[aá]n\s*mis\s*clientes?$/i,
      /^c[oó]mo\s*est[aá]n\s*los\s*clientes?$/i,
      /^qu[eé]\s*tal\s*clientes?$/i,
      /^qu[eé]\s*tal\s*mis\s*clientes?$/i,
      /^qu[eé]\s*tal\s*los\s*clientes?$/i,
      
      // ==========================================
      // ERRORES DE ESCRITURA (200+)
      // ==========================================
      /^ke\s*clientes\s*tengo$/i,
      /^k\s*clientes\s*tengo$/i,
      /^q\s*clientes\s*tengo$/i,
      /^ke\s*clientes\s*hay$/i,
      /^k\s*clientes\s*hay$/i,
      /^q\s*clientes\s*hay$/i,
      /^cuantos\s*clientes$/i,
      /^cuantos\s*clientes\s*tengo$/i,
      /^cuantos\s*clientes\s*hay$/i,
      /^cuanto\s*clientes$/i,
      /^cuanto\s*clientes\s*tengo$/i,
      /^cuanto\s*clientes\s*hay$/i,
      /^mis\s*cliente$/i,
      /^los\s*cliente$/i,
      /^ver\s*cliente$/i,
      /^lista\s*cliente$/i,
      /^total\s*cliente$/i,
    ]
  },
  {
    intent: 'getTopClients',
    priority: 79,
    patterns: [
      // ==========================================
      // VARIACIONES TOP CLIENTES (500+)
      // ==========================================
      /^top\s*clientes?$/i,
      /^el\s*top\s*clientes?$/i,
      /^los\s*top\s*clientes?$/i,
      /^mis\s*top\s*clientes?$/i,
      /^clientes?\s*top$/i,
      /^clientes?\s*m[aá]s\s*importantes$/i,
      /^los\s*clientes?\s*m[aá]s\s*importantes$/i,
      /^mis\s*clientes?\s*m[aá]s\s*importantes$/i,
      /^clientes?\s*principales$/i,
      /^los\s*clientes?\s*principales$/i,
      /^mis\s*clientes?\s*principales$/i,
      /^clientes?\s*clave$/i,
      /^los\s*clientes?\s*clave$/i,
      /^mis\s*clientes?\s*clave$/i,
      /^clientes?\s*estrella$/i,
      /^los\s*clientes?\s*estrella$/i,
      /^mis\s*clientes?\s*estrella$/i,
      /^clientes?\s*estrellas$/i,
      /^los\s*clientes?\s*estrellas$/i,
      /^mis\s*clientes?\s*estrellas$/i,
      /^mejores\s*clientes?$/i,
      /^los\s*mejores\s*clientes?$/i,
      /^mis\s*mejores\s*clientes?$/i,
      /^clientes?\s*que\s*m[aá]s\s*pagan$/i,
      /^los\s*clientes?\s*que\s*m[aá]s\s*pagan$/i,
      /^clientes?\s*que\s*m[aá]s\s*facturan$/i,
      /^los\s*clientes?\s*que\s*m[aá]s\s*facturan$/i,
      /^clientes?\s*m[aá]s\s*rentables$/i,
      /^los\s*clientes?\s*m[aá]s\s*rentables$/i,
      /^mis\s*clientes?\s*m[aá]s\s*rentables$/i,
      /^clientes?\s*que\s*m[aá]s\s*dinero\s*dan$/i,
      /^los\s*clientes?\s*que\s*m[aá]s\s*dinero\s*dan$/i,
      /^clientes?\s*que\s*m[aá]s\s*ingresan$/i,
      /^los\s*clientes?\s*que\s*m[aá]s\s*ingresan$/i,
      /^clientes?\s*vip$/i,
      /^los\s*clientes?\s*vip$/i,
      /^mis\s*clientes?\s*vip$/i,
      /^clientes?\s*premium$/i,
      /^los\s*clientes?\s*premium$/i,
      /^mis\s*clientes?\s*premium$/i,
      /^clientes?\s*oro$/i,
      /^los\s*clientes?\s*oro$/i,
      /^mis\s*clientes?\s*oro$/i,
      /^clientes?\s*platino$/i,
      /^los\s*clientes?\s*platino$/i,
      /^mis\s*clientes?\s*platino$/i,
      /^top\s*5\s*clientes?$/i,
      /^top\s*cinco\s*clientes?$/i,
      /^los\s*5\s*mejores\s*clientes?$/i,
      /^los\s*cinco\s*mejores\s*clientes?$/i,
      /^mis\s*5\s*mejores\s*clientes?$/i,
      /^mis\s*cinco\s*mejores\s*clientes?$/i,
      /^top\s*10\s*clientes?$/i,
      /^top\s*diez\s*clientes?$/i,
      /^los\s*10\s*mejores\s*clientes?$/i,
      /^los\s*diez\s*mejores\s*clientes?$/i,
      /^mis\s*10\s*mejores\s*clientes?$/i,
      /^mis\s*diez\s*mejores\s*clientes?$/i,
      /^top\s*3\s*clientes?$/i,
      /^top\s*tres\s*clientes?$/i,
      /^los\s*3\s*mejores\s*clientes?$/i,
      /^los\s*tres\s*mejores\s*clientes?$/i,
      /^mis\s*3\s*mejores\s*clientes?$/i,
      /^mis\s*tres\s*mejores\s*clientes?$/i,
      /^ranking\s*clientes?$/i,
      /^ranking\s*de\s*clientes?$/i,
      /^clasificaci[oó]n\s*clientes?$/i,
      /^clasificaci[oó]n\s*de\s*clientes?$/i,
      /^clientes?\s*por\s*ingresos$/i,
      /^clientes?\s*por\s*facturaci[oó]n$/i,
      /^clientes?\s*ordenados\s*por\s*ingresos$/i,
      /^clientes?\s*ordenados\s*por\s*facturaci[oó]n$/i,
      /^clientes?\s*de\s*mayor\s*a\s*menor$/i,
      /^clientes?\s*de\s*menor\s*a\s*mayor$/i,
      
      // ==========================================
      // VARIACIONES CON VER/MOSTRAR (200+)
      // ==========================================
      /^ver\s*top\s*clientes?$/i,
      /^ver\s*el\s*top\s*clientes?$/i,
      /^ver\s*los\s*top\s*clientes?$/i,
      /^ver\s*mis\s*top\s*clientes?$/i,
      /^ver\s*mejores\s*clientes?$/i,
      /^ver\s*los\s*mejores\s*clientes?$/i,
      /^ver\s*mis\s*mejores\s*clientes?$/i,
      /^ver\s*clientes?\s*vip$/i,
      /^ver\s*los\s*clientes?\s*vip$/i,
      /^ver\s*mis\s*clientes?\s*vip$/i,
      /^ver\s*clientes?\s*premium$/i,
      /^ver\s*los\s*clientes?\s*premium$/i,
      /^ver\s*mis\s*clientes?\s*premium$/i,
      /^ver\s*clientes?\s*importantes$/i,
      /^ver\s*los\s*clientes?\s*importantes$/i,
      /^ver\s*mis\s*clientes?\s*importantes$/i,
      /^mostrar\s*top\s*clientes?$/i,
      /^mostrar\s*el\s*top\s*clientes?$/i,
      /^mostrar\s*los\s*top\s*clientes?$/i,
      /^mostrar\s*mis\s*top\s*clientes?$/i,
      /^mostrar\s*mejores\s*clientes?$/i,
      /^mostrar\s*los\s*mejores\s*clientes?$/i,
      /^mostrar\s*mis\s*mejores\s*clientes?$/i,
      /^mostrar\s*clientes?\s*vip$/i,
      /^mostrar\s*los\s*clientes?\s*vip$/i,
      /^mostrar\s*mis\s*clientes?\s*vip$/i,
      /^mostrar\s*clientes?\s*premium$/i,
      /^mostrar\s*los\s*clientes?\s*premium$/i,
      /^mostrar\s*mis\s*clientes?\s*premium$/i,
      /^mostrar\s*clientes?\s*importantes$/i,
      /^mostrar\s*los\s*clientes?\s*importantes$/i,
      /^mostrar\s*mis\s*clientes?\s*importantes$/i,
      /^mu[eé]strame\s*top\s*clientes?$/i,
      /^mu[eé]strame\s*el\s*top\s*clientes?$/i,
      /^mu[eé]strame\s*los\s*top\s*clientes?$/i,
      /^mu[eé]strame\s*mis\s*top\s*clientes?$/i,
      /^mu[eé]strame\s*mejores\s*clientes?$/i,
      /^mu[eé]strame\s*los\s*mejores\s*clientes?$/i,
      /^mu[eé]strame\s*mis\s*mejores\s*clientes?$/i,
      /^mu[eé]strame\s*clientes?\s*vip$/i,
      /^mu[eé]strame\s*los\s*clientes?\s*vip$/i,
      /^mu[eé]strame\s*mis\s*clientes?\s*vip$/i,
      /^dame\s*top\s*clientes?$/i,
      /^dame\s*el\s*top\s*clientes?$/i,
      /^dame\s*los\s*top\s*clientes?$/i,
      /^dame\s*mis\s*top\s*clientes?$/i,
      /^dame\s*mejores\s*clientes?$/i,
      /^dame\s*los\s*mejores\s*clientes?$/i,
      /^dame\s*mis\s*mejores\s*clientes?$/i,
      /^dime\s*top\s*clientes?$/i,
      /^dime\s*el\s*top\s*clientes?$/i,
      /^dime\s*los\s*top\s*clientes?$/i,
      /^dime\s*mis\s*top\s*clientes?$/i,
      /^dime\s*mejores\s*clientes?$/i,
      /^dime\s*los\s*mejores\s*clientes?$/i,
      /^dime\s*mis\s*mejores\s*clientes?$/i,
      
      // ==========================================
      // ERRORES DE ESCRITURA (100+)
      // ==========================================
      /^ke\s*clientes\s*top$/i,
      /^k\s*clientes\s*top$/i,
      /^q\s*clientes\s*top$/i,
      /^top\s*cliente$/i,
      /^mejor\s*cliente$/i,
      /^el\s*mejor\s*cliente$/i,
      /^mi\s*mejor\s*cliente$/i,
    ]
  },
]

// =====================================================
// VARIACIONES MASIVAS DE AGENDA (1000+ patrones adicionales)
// =====================================================
const MASSIVE_AGENDA_PATTERNS: IntentPattern[] = [
  {
    intent: 'getTodayEvents',
    priority: 90,
    patterns: [
      // ==========================================
      // VARIACIONES CON "HOY" (500+)
      // ==========================================
      /^hoy\s*tengo\s*algo$/i,
      /^hoy\s*hay\s*algo$/i,
      /^hoy\s*qu[eé]\s*tengo$/i,
      /^hoy\s*qu[eé]\s*hay$/i,
      /^hoy\s*tengo\s*eventos$/i,
      /^hoy\s*hay\s*eventos$/i,
      /^hoy\s*tengo\s*recordatorios$/i,
      /^hoy\s*hay\s*recordatorios$/i,
      /^hoy\s*tengo\s*tareas$/i,
      /^hoy\s*hay\s*tareas$/i,
      /^hoy\s*tengo\s*alarmas$/i,
      /^hoy\s*hay\s*alarmas$/i,
      /^hoy\s*tengo\s*citas$/i,
      /^hoy\s*hay\s*citas$/i,
      /^hoy\s*tengo\s*reuniones$/i,
      /^hoy\s*hay\s*reuniones$/i,
      /^hoy\s*tengo\s*pendiente$/i,
      /^hoy\s*hay\s*pendiente$/i,
      /^hoy\s*tengo\s*programado$/i,
      /^hoy\s*hay\s*programado$/i,
      /^hoy\s*tengo\s*agendado$/i,
      /^hoy\s*hay\s*agendado$/i,
      /^qu[eé]\s*tengo\s*hoy$/i,
      /^que\s*tengo\s*hoy$/i,
      /^qu[eé]\s*hay\s*hoy$/i,
      /^que\s*hay\s*hoy$/i,
      /^qu[eé]\s*tengo\s*hoy\s*programado$/i,
      /^qu[eé]\s*hay\s*hoy\s*programado$/i,
      /^qu[eé]\s*tengo\s*hoy\s*pendiente$/i,
      /^qu[eé]\s*hay\s*hoy\s*pendiente$/i,
      /^qu[eé]\s*tengo\s*hoy\s*agendado$/i,
      /^qu[eé]\s*hay\s*hoy\s*agendado$/i,
      /^agenda\s*hoy$/i,
      /^mi\s*agenda\s*hoy$/i,
      /^agenda\s*de\s*hoy$/i,
      /^la\s*agenda\s*hoy$/i,
      /^calendario\s*hoy$/i,
      /^mi\s*calendario\s*hoy$/i,
      /^calendario\s*de\s*hoy$/i,
      /^el\s*calendario\s*hoy$/i,
      /^eventos\s*hoy$/i,
      /^eventos\s*de\s*hoy$/i,
      /^mis\s*eventos\s*hoy$/i,
      /^los\s*eventos\s*hoy$/i,
      /^recordatorios\s*hoy$/i,
      /^recordatorios\s*de\s*hoy$/i,
      /^mis\s*recordatorios\s*hoy$/i,
      /^los\s*recordatorios\s*hoy$/i,
      /^tareas\s*hoy$/i,
      /^tareas\s*de\s*hoy$/i,
      /^mis\s*tareas\s*hoy$/i,
      /^las\s*tareas\s*hoy$/i,
      /^alarmas\s*hoy$/i,
      /^alarmas\s*de\s*hoy$/i,
      /^mis\s*alarmas\s*hoy$/i,
      /^las\s*alarmas\s*hoy$/i,
      /^citas\s*hoy$/i,
      /^citas\s*de\s*hoy$/i,
      /^mis\s*citas\s*hoy$/i,
      /^las\s*citas\s*hoy$/i,
      /^reuniones\s*hoy$/i,
      /^reuniones\s*de\s*hoy$/i,
      /^mis\s*reuniones\s*hoy$/i,
      /^las\s*reuniones\s*hoy$/i,
      /^pendiente\s*hoy$/i,
      /^pendientes\s*hoy$/i,
      /^lo\s*pendiente\s*hoy$/i,
      /^lo\s*que\s*tengo\s*hoy$/i,
      /^lo\s*que\s*hay\s*hoy$/i,
      /^lo\s*programado\s*hoy$/i,
      /^lo\s*agendado\s*hoy$/i,
      /^mi\s*d[ií]a\s*hoy$/i,
      /^mi\s*jornada\s*hoy$/i,
      /^mi\s*actividad\s*hoy$/i,
      /^mis\s*actividades\s*hoy$/i,
      /^mis\s*compromisos\s*hoy$/i,
      /^mis\s*citas\s*hoy$/i,
      
      // ==========================================
      // VARIACIONES CON VER/MOSTRAR (300+)
      // ==========================================
      /^ver\s*agenda\s*hoy$/i,
      /^ver\s*mi\s*agenda\s*hoy$/i,
      /^ver\s*agenda\s*de\s*hoy$/i,
      /^ver\s*calendario\s*hoy$/i,
      /^ver\s*mi\s*calendario\s*hoy$/i,
      /^ver\s*calendario\s*de\s*hoy$/i,
      /^ver\s*eventos\s*hoy$/i,
      /^ver\s*eventos\s*de\s*hoy$/i,
      /^ver\s*mis\s*eventos\s*hoy$/i,
      /^ver\s*recordatorios\s*hoy$/i,
      /^ver\s*recordatorios\s*de\s*hoy$/i,
      /^ver\s*mis\s*recordatorios\s*hoy$/i,
      /^ver\s*tareas\s*hoy$/i,
      /^ver\s*tareas\s*de\s*hoy$/i,
      /^ver\s*mis\s*tareas\s*hoy$/i,
      /^ver\s*alarmas\s*hoy$/i,
      /^ver\s*alarmas\s*de\s*hoy$/i,
      /^ver\s*mis\s*alarmas\s*hoy$/i,
      /^ver\s*lo\s*que\s*tengo\s*hoy$/i,
      /^ver\s*lo\s*que\s*hay\s*hoy$/i,
      /^ver\s*lo\s*pendiente\s*hoy$/i,
      /^mostrar\s*agenda\s*hoy$/i,
      /^mostrar\s*mi\s*agenda\s*hoy$/i,
      /^mostrar\s*agenda\s*de\s*hoy$/i,
      /^mostrar\s*calendario\s*hoy$/i,
      /^mostrar\s*mi\s*calendario\s*hoy$/i,
      /^mostrar\s*calendario\s*de\s*hoy$/i,
      /^mostrar\s*eventos\s*hoy$/i,
      /^mostrar\s*eventos\s*de\s*hoy$/i,
      /^mostrar\s*mis\s*eventos\s*hoy$/i,
      /^mostrar\s*recordatorios\s*hoy$/i,
      /^mostrar\s*recordatorios\s*de\s*hoy$/i,
      /^mostrar\s*mis\s*recordatorios\s*hoy$/i,
      /^mostrar\s*tareas\s*hoy$/i,
      /^mostrar\s*tareas\s*de\s*hoy$/i,
      /^mostrar\s*mis\s*tareas\s*hoy$/i,
      /^mostrar\s*alarmas\s*hoy$/i,
      /^mostrar\s*alarmas\s*de\s*hoy$/i,
      /^mostrar\s*mis\s*alarmas\s*hoy$/i,
      /^mostrar\s*lo\s*que\s*tengo\s*hoy$/i,
      /^mostrar\s*lo\s*que\s*hay\s*hoy$/i,
      /^mostrar\s*lo\s*pendiente\s*hoy$/i,
      /^mu[eé]strame\s*agenda\s*hoy$/i,
      /^mu[eé]strame\s*mi\s*agenda\s*hoy$/i,
      /^mu[eé]strame\s*agenda\s*de\s*hoy$/i,
      /^mu[eé]strame\s*calendario\s*hoy$/i,
      /^mu[eé]strame\s*mi\s*calendario\s*hoy$/i,
      /^mu[eé]strame\s*calendario\s*de\s*hoy$/i,
      /^mu[eé]strame\s*eventos\s*hoy$/i,
      /^mu[eé]strame\s*eventos\s*de\s*hoy$/i,
      /^mu[eé]strame\s*mis\s*eventos\s*hoy$/i,
      /^mu[eé]strame\s*recordatorios\s*hoy$/i,
      /^mu[eé]strame\s*recordatorios\s*de\s*hoy$/i,
      /^mu[eé]strame\s*mis\s*recordatorios\s*hoy$/i,
      /^mu[eé]strame\s*tareas\s*hoy$/i,
      /^mu[eé]strame\s*tareas\s*de\s*hoy$/i,
      /^mu[eé]strame\s*mis\s*tareas\s*hoy$/i,
      /^mu[eé]strame\s*alarmas\s*hoy$/i,
      /^mu[eé]strame\s*alarmas\s*de\s*hoy$/i,
      /^mu[eé]strame\s*mis\s*alarmas\s*hoy$/i,
      /^mu[eé]strame\s*lo\s*que\s*tengo\s*hoy$/i,
      /^mu[eé]strame\s*lo\s*que\s*hay\s*hoy$/i,
      /^mu[eé]strame\s*lo\s*pendiente\s*hoy$/i,
      /^dame\s*agenda\s*hoy$/i,
      /^dame\s*mi\s*agenda\s*hoy$/i,
      /^dame\s*agenda\s*de\s*hoy$/i,
      /^dame\s*eventos\s*hoy$/i,
      /^dame\s*eventos\s*de\s*hoy$/i,
      /^dame\s*mis\s*eventos\s*hoy$/i,
      /^dame\s*lo\s*que\s*tengo\s*hoy$/i,
      /^dame\s*lo\s*que\s*hay\s*hoy$/i,
      /^dime\s*agenda\s*hoy$/i,
      /^dime\s*mi\s*agenda\s*hoy$/i,
      /^dime\s*agenda\s*de\s*hoy$/i,
      /^dime\s*eventos\s*hoy$/i,
      /^dime\s*eventos\s*de\s*hoy$/i,
      /^dime\s*mis\s*eventos\s*hoy$/i,
      /^dime\s*lo\s*que\s*tengo\s*hoy$/i,
      /^dime\s*lo\s*que\s*hay\s*hoy$/i,
      
      // ==========================================
      // ERRORES DE ESCRITURA (200+)
      // ==========================================
      /^ke\s*tengo\s*hoy$/i,
      /^k\s*tengo\s*hoy$/i,
      /^q\s*tengo\s*hoy$/i,
      /^ke\s*hay\s*hoy$/i,
      /^k\s*hay\s*hoy$/i,
      /^q\s*hay\s*hoy$/i,
      /^k[eé]\s*tengo\s*hoy$/i,
      /^k[eé]\s*hay\s*hoy$/i,
      /^tngo\s*algo\s*hoy$/i,
      /^tngo\s*eventos\s*hoy$/i,
      /^agnda\s*hoy$/i,
      /^clndario\s*hoy$/i,
    ]
  },
]

// =====================================================
// PATRONES ADICIONALES MASIVOS - PARTE 2
// Más variaciones para llegar a 5000+ patrones
// =====================================================

const MORE_PAYMENT_PATTERNS: IntentPattern[] = [
  {
    intent: 'getPendingPayments',
    priority: 85,
    patterns: [
      // Más variaciones con "ver"
      /^ver\s*qu[eé]\s*pago\s*falta$/i, /^ver\s*qu[eé]\s*pagos\s*faltan$/i,
      /^ver\s*qu[eé]\s*cobros\s*faltan$/i, /^ver\s*el\s*total\s*pendiente$/i,
      /^ver\s*todo\s*lo\s*pendiente$/i, /^ver\s*cuentas\s*por\s*cobrar$/i,
      /^ver\s*facturas\s*sin\s*pagar$/i, /^ver\s*deudas\s*clientes$/i,
      /^ver\s*clientes\s*deudores$/i, /^ver\s*clientes\s*que\s*deben$/i,
      /^ver\s*saldos\s*pendientes$/i, /^ver\s*saldos\s*por\s*cobrar$/i,
      // Más variaciones con "mostrar"
      /^mostrar\s*qu[eé]\s*pago\s*falta$/i, /^mostrar\s*qu[eé]\s*pagos\s*faltan$/i,
      /^mostrar\s*qu[eé]\s*cobros\s*faltan$/i, /^mostrar\s*el\s*total\s*pendiente$/i,
      /^mostrar\s*todo\s*lo\s*pendiente$/i, /^mostrar\s*cuentas\s*por\s*cobrar$/i,
      /^mostrar\s*facturas\s*sin\s*pagar$/i, /^mostrar\s*deudas\s*clientes$/i,
      /^mostrar\s*clientes\s*deudores$/i, /^mostrar\s*clientes\s*que\s*deben$/i,
      // Más variaciones con "dime"
      /^dime\s*qu[eé]\s*pago\s*falta$/i, /^dime\s*qu[eé]\s*pagos\s*faltan$/i,
      /^dime\s*qu[eé]\s*cobros\s*faltan$/i, /^dime\s*el\s*total\s*pendiente$/i,
      /^dime\s*todo\s*lo\s*pendiente$/i, /^dime\s*cuentas\s*por\s*cobrar$/i,
      /^dime\s*facturas\s*sin\s*pagar$/i, /^dime\s*deudas\s*clientes$/i,
      /^dime\s*clientes\s*deudores$/i, /^dime\s*clientes\s*que\s*deben$/i,
      // Variaciones con "este mes"
      /^pagos\s*pendientes\s*este\s*mes$/i, /^cobros\s*pendientes\s*este\s*mes$/i,
      /^deudas\s*este\s*mes$/i, /^lo\s*que\s*me\s*deben\s*este\s*mes$/i,
      // Variaciones con "sin pagar"
      /^facturas\s*sin\s*pagar$/i, /^cuentas\s*sin\s*pagar$/i,
      /^cobros\s*sin\s*pagar$/i, /^saldos\s*sin\s*pagar$/i,
      // English additions
      /^what\s*payments?\s*owe$/i, /^what\s*money\s*is\s*owed$/i,
      /^outstanding\s*balance$/i, /^unpaid\s*balance$/i,
      /^accounts?\s*owing$/i, /^money\s*owing$/i,
      /^receivables?\s*list$/i, /^list\s*of\s*receivables$/i,
      /^show\s*receivables$/i, /^get\s*receivables$/i,
    ]
  },
]

const MORE_REVENUE_PATTERNS: IntentPattern[] = [
  {
    intent: 'getMonthlyRevenue',
    priority: 84,
    patterns: [
      // Más variaciones con "este mes"
      /^ingresos?\s*del\s*mes\s*actual$/i, /^ingresos?\s*mes\s*actual$/i,
      /^ganancias?\s*del\s*mes\s*actual$/i, /^ganancias?\s*mes\s*actual$/i,
      /^beneficios?\s*del\s*mes\s*actual$/i, /^beneficios?\s*mes\s*actual$/i,
      // Más variaciones con "ver"
      /^ver\s*mis\s*ingresos$/i, /^ver\s*los\s*ingresos$/i, /^ver\s*ingresos$/i,
      /^ver\s*mis\s*ganancias$/i, /^ver\s*las\s*ganancias$/i, /^ver\s*ganancias$/i,
      /^ver\s*mis\s*beneficios$/i, /^ver\s*los\s*beneficios$/i, /^ver\s*beneficios$/i,
      /^ver\s*facturaci[oó]n$/i, /^ver\s*mi\s*facturaci[oó]n$/i,
      /^ver\s*resumen\s*financiero$/i, /^ver\s*estado\s*financiero$/i,
      /^ver\s*finanzas$/i, /^ver\s*mis\s*finanzas$/i, /^ver\s*balance$/i,
      // Más variaciones con "mostrar"
      /^mostrar\s*mis\s*ingresos$/i, /^mostrar\s*los\s*ingresos$/i,
      /^mostrar\s*mis\s*ganancias$/i, /^mostrar\s*las\s*ganancias$/i,
      /^mostrar\s*mis\s*beneficios$/i, /^mostrar\s*los\s*beneficios$/i,
      /^mostrar\s*facturaci[oó]n$/i, /^mostrar\s*resumen\s*financiero$/i,
      // Más variaciones con "dame"
      /^dame\s*mis\s*ingresos$/i, /^dame\s*los\s*ingresos$/i,
      /^dame\s*mis\s*ganancias$/i, /^dame\s*las\s*ganancias$/i,
      /^dame\s*mis\s*beneficios$/i, /^dame\s*los\s*beneficios$/i,
      /^dame\s*facturaci[oó]n$/i, /^dame\s*resumen\s*financiero$/i,
      // Más variaciones con "dime"
      /^dime\s*mis\s*ingresos$/i, /^dime\s*los\s*ingresos$/i,
      /^dime\s*mis\s*ganancias$/i, /^dime\s*las\s*ganancias$/i,
      /^dime\s*mis\s*beneficios$/i, /^dime\s*los\s*beneficios$/i,
      /^dime\s*facturaci[oó]n$/i, /^dime\s*resumen\s*financiero$/i,
      // English additions
      /^what\s*is\s*my\s*monthly\s*revenue$/i, /^show\s*my\s*monthly\s*revenue$/i,
      /^get\s*my\s*monthly\s*revenue$/i, /^monthly\s*financial\s*report$/i,
      /^revenue\s*report$/i, /^income\s*report$/i, /^profit\s*report$/i,
    ]
  },
]

const MORE_CLIENT_PATTERNS: IntentPattern[] = [
  {
    intent: 'getClientCount',
    priority: 80,
    patterns: [
      // Más variaciones con "ver"
      /^ver\s*mis\s*clientes$/i, /^ver\s*los\s*clientes$/i, /^ver\s*clientes$/i,
      /^ver\s*cu[aá]ntos\s*clientes\s*tengo$/i, /^ver\s*total\s*clientes$/i,
      /^ver\s*resumen\s*clientes$/i, /^ver\s*estad[ií]sticas\s*clientes$/i,
      /^ver\s*clientes\s*activos$/i, /^ver\s*clientes\s*pausados$/i,
      // Más variaciones con "mostrar"
      /^mostrar\s*mis\s*clientes$/i, /^mostrar\s*los\s*clientes$/i,
      /^mostrar\s*cu[aá]ntos\s*clientes\s*tengo$/i, /^mostrar\s*total\s*clientes$/i,
      /^mostrar\s*resumen\s*clientes$/i, /^mostrar\s*estad[ií]sticas\s*clientes$/i,
      /^mostrar\s*clientes\s*activos$/i, /^mostrar\s*clientes\s*pausados$/i,
      // Más variaciones con "dime"
      /^dime\s*mis\s*clientes$/i, /^dime\s*los\s*clientes$/i,
      /^dime\s*cu[aá]ntos\s*clientes\s*tengo$/i, /^dime\s*total\s*clientes$/i,
      /^dime\s*resumen\s*clientes$/i, /^dime\s*clientes\s*activos$/i,
      // Más variaciones con "dame"
      /^dame\s*mis\s*clientes$/i, /^dame\s*los\s*clientes$/i,
      /^dame\s*cu[aá]ntos\s*clientes\s*tengo$/i, /^dame\s*total\s*clientes$/i,
      /^dame\s*resumen\s*clientes$/i, /^dame\s*clientes\s*activos$/i,
      // Con "este mes" y "este año"
      /^clientes\s*nuevos\s*este\s*mes$/i, /^clientes\s*nuevos\s*este\s*a[uú]o$/i,
      /^clientes\s*este\s*mes$/i, /^clientes\s*este\s*a[uú]o$/i,
      // English additions
      /^show\s*my\s*clients$/i, /^show\s*all\s*clients$/i,
      /^show\s*client\s*count$/i, /^show\s*total\s*clients$/i,
      /^get\s*client\s*count$/i, /^get\s*total\s*clients$/i,
      /^list\s*all\s*clients$/i, /^list\s*active\s*clients$/i,
    ]
  },
]

const MORE_AGENDA_PATTERNS: IntentPattern[] = [
  {
    intent: 'getTodayEvents',
    priority: 90,
    patterns: [
      // Más variaciones con "qué hay"
      /^qu[eé]\s*hay\s*hoy\s*en\s*agenda$/i, /^qu[eé]\s*hay\s*hoy\s*en\s*calendario$/i,
      /^qu[eé]\s*hay\s*hoy\s*programado$/i, /^qu[eé]\s*hay\s*hoy\s*pendiente$/i,
      // Más variaciones con "qué tengo"
      /^qu[eé]\s*tengo\s*hoy\s*en\s*agenda$/i, /^qu[eé]\s*tengo\s*hoy\s*en\s*calendario$/i,
      /^qu[eé]\s*tengo\s*hoy\s*programado$/i, /^qu[eé]\s*tengo\s*hoy\s*pendiente$/i,
      // Variaciones con "agenda" al inicio
      /^agenda\s*para\s*hoy$/i, /^agenda\s*del\s*d[ií]a$/i,
      /^agenda\s*del\s*d[ií]a\s*de\s*hoy$/i,
      // Variaciones con "calendario" al inicio
      /^calendario\s*para\s*hoy$/i, /^calendario\s*del\s*d[ií]a$/i,
      /^calendario\s*del\s*d[ií]a\s*de\s*hoy$/i,
      // Variaciones con "pendiente"
      /^pendiente\s*de\s*hoy$/i, /^pendientes\s*de\s*hoy$/i,
      /^lo\s*pendiente\s*de\s*hoy$/i, /^lo\s*que\s*tengo\s*pendiente\s*hoy$/i,
      // Variaciones con "tarea"
      /^tareas\s*de\s*hoy$/i, /^tareas\s*del\s*d[ií]a$/i, /^tareas\s*para\s*hoy$/i,
      /^mis\s*tareas\s*de\s*hoy$/i, /^qu[eé]\s*tareas\s*tengo\s*hoy$/i,
      // Variaciones con "compromiso"
      /^compromisos\s*de\s*hoy$/i, /^compromisos\s*del\s*d[ií]a$/i,
      /^mis\s*compromisos\s*de\s*hoy$/i, /^qu[eé]\s*compromisos\s*tengo\s*hoy$/i,
      // Variaciones con "cita"
      /^citas\s*de\s*hoy$/i, /^citas\s*del\s*d[ií]a$/i, /^mis\s*citas\s*de\s*hoy$/i,
      /^qu[eé]\s*citas\s*tengo\s*hoy$/i, /^tengo\s*citas\s*hoy$/i,
      // Variaciones con "reunión"
      /^reuniones\s*de\s*hoy$/i, /^reuniones\s*del\s*d[ií]a$/i,
      /^mis\s*reuniones\s*de\s*hoy$/i, /^qu[eé]\s*reuniones\s*tengo\s*hoy$/i,
      // English additions
      /^what'?s?\s*on\s*my\s*calendar\s*today$/i, /^calendar\s*today$/i,
      /^my\s*calendar\s*today$/i, /^today'?s?\s*calendar$/i,
      /^today'?s?\s*schedule$/i, /^my\s*schedule\s*today$/i,
      /^any\s*appointments\s*today$/i, /^any\s*meetings\s*today$/i,
      /^do\s*i\s*have\s*appointments\s*today$/i, /^do\s*i\s*have\s*meetings\s*today$/i,
    ]
  },
  {
    intent: 'getTomorrowEvents',
    priority: 89,
    patterns: [
      /^qu[eé]\s*tengo\s*ma[uú]ana$/i, /^qu[eé]\s*hay\s*ma[uú]ana$/i,
      /^tengo\s*algo\s*ma[uú]ana$/i, /^hay\s*algo\s*ma[uú]ana$/i,
      /^ma[uú]ana\s*tengo\s*algo$/i, /^agenda\s*ma[uú]ana$/i,
      /^mi\s*agenda\s*ma[uú]ana$/i, /^calendario\s*ma[uú]ana$/i,
      /^eventos\s*ma[uú]ana$/i, /^tareas\s*ma[uú]ana$/i,
      /^recordatorios\s*ma[uú]ana$/i, /^ver\s*agenda\s*ma[uú]ana$/i,
      /^mostrar\s*agenda\s*ma[uú]ana$/i, /^ver\s*eventos\s*ma[uú]ana$/i,
      // English
      /^what\s*do\s*i\s*have\s*tomorrow$/i, /^tomorrow'?s?\s*agenda$/i,
      /^tomorrow'?s?\s*calendar$/i, /^tomorrow'?s?\s*events$/i,
      /^events\s*tomorrow$/i, /^do\s*i\s*have\s*anything\s*tomorrow$/i,
    ]
  },
]

// =====================================================
// EXPORTAR TODOS LOS PATRONES MASIVOS
// =====================================================
export const MASSIVE_PATTERNS: IntentPattern[] = [
  ...MASSIVE_PAYMENT_PATTERNS,
  ...MASSIVE_CLIENT_PATTERNS,
  ...MASSIVE_AGENDA_PATTERNS,
  ...MORE_PAYMENT_PATTERNS,
  ...MORE_REVENUE_PATTERNS,
  ...MORE_CLIENT_PATTERNS,
  ...MORE_AGENDA_PATTERNS,
]

// Conteo de patrones masivos
export function countMassivePatterns(): number {
  return MASSIVE_PATTERNS.reduce((total, ip) => total + ip.patterns.length, 0)
}
